# Generated by Django 3.2.10 on 2022-06-07 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0017_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Site',
            new_name='SiteLocal',
        ),
    ]
