# Generated by Django 3.2.10 on 2022-06-07 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0018_rename_site_sitelocal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название Сайта')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='Описание сайта')),
                ('path', models.CharField(max_length=100, unique=True, verbose_name='Пусть к сайту')),
                ('image', models.ImageField(upload_to='')),
                ('cataloge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.cataloge')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.sitecategoty', verbose_name='Категория сайта')),
                ('languege', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.languege', verbose_name='Язык сайта')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='archive.tag')),
            ],
        ),
        migrations.DeleteModel(
            name='SiteLocal',
        ),
        migrations.CreateModel(
            name='Siteremote',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('archive.site',),
        ),
        migrations.CreateModel(
            name='SiteLocal',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('archive.site',),
        ),
    ]
