# Generated by Django 3.2.10 on 2022-06-07 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('archive', '0019_auto_20220607_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cataloge',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название каталога'),
        ),
    ]
