# Generated by Django 3.2.10 on 2022-05-22 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kma', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='defaultweb',
            name='name',
            field=models.CharField(max_length=50, unique=True, verbose_name='Имя веба'),
        ),
    ]
