# Generated by Django 3.2.10 on 2022-05-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kma', '0002_alter_defaultweb_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short', models.CharField(max_length=2, unique=True, verbose_name='Код страны')),
                ('phone', models.CharField(max_length=15, verbose_name='Валидный номер')),
                ('ru_full_name', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Русское название')),
            ],
        ),
    ]
