# Generated by Django 3.2.10 on 2022-09-27 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kma', '0003_phonenumber'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('iso', models.CharField(max_length=2, primary_key=True, serialize=False, verbose_name='Код iso языка')),
                ('russian_name', models.CharField(blank=True, max_length=25, verbose_name='Русское название')),
            ],
            options={
                'ordering': ['iso'],
            },
        ),
        migrations.CreateModel(
            name='OfferPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Оффер')),
            ],
            options={
                'verbose_name': 'Оффер',
                'verbose_name_plural': 'Офферы',
            },
        ),
        migrations.AlterModelOptions(
            name='defaultweb',
            options={'verbose_name': 'Веб по умолчанию', 'verbose_name_plural': 'Вебы по умолчаниюа'},
        ),
        migrations.AlterModelOptions(
            name='phonenumber',
            options={'verbose_name': 'Валидный номер', 'verbose_name_plural': 'Валидные номера'},
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='currency',
            field=models.CharField(blank=True, max_length=5, verbose_name='Валюта'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='langs',
            field=models.CharField(blank=True, max_length=15, verbose_name='Языки гео'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='phone_code',
            field=models.CharField(blank=True, max_length=15, verbose_name='Моб код страны'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='words',
            field=models.JSONField(default={'templates': [], 'words': []}, verbose_name='Слова под гео'),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='short',
            field=models.CharField(max_length=2, unique=True, verbose_name='Код страны ISO'),
        ),
    ]
