# Generated by Django 3.2.10 on 2023-02-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kma', '0005_userapikey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='phonenumber',
            name='id',
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='short',
            field=models.CharField(max_length=2, primary_key=True, serialize=False, unique=True, verbose_name='Код страны ISO'),
        ),
    ]
