# Generated by Django 3.2.10 on 2023-02-25 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kma', '0007_rename_phonenumber_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='country',
            old_name='short',
            new_name='iso',
        ),
    ]
