# Generated by Django 3.2.10 on 2023-02-26 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kma', '0009_country_language'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AlterField(
            model_name='country',
            name='ru_full_name',
            field=models.CharField(blank=True, max_length=60, unique=True, verbose_name='Русское название'),
        ),
    ]
