# Generated by Django 3.2.10 on 2023-02-26 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kma', '0010_auto_20230226_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='iso3',
            field=models.CharField(blank=True, max_length=3, null=True, unique=True, verbose_name='ISO 3'),
        ),
    ]
